### ISSUE TITLE
CLOSED

### ISSUE THREAD

**Issue by ZfsrGhS953** [lefela4/agar_bots_v5#3]
A completely non-functional mess made out of some folders from MultiOgar-Edited, made-up config files and a badly obfuscated Singa Bots script.

**Comment by lefela4** [comment]
@ZfsrGhS953 You are just kid leave me alone and I will not give my deobsucate bots. It not singa cz it shit.

**Comment by ZfsrGhS953** [comment]
@lefela4 What are you talking about? First of all, prove that I'm a kid. Second, don't even try to tell that it isn't Singa. I looked at your userscript and can tell you that it has parts of code from Singa Bots, AgarAPI Feeder Bots and PolarsBots. You stole **THREE** bot scripts that were developed by skilled programmers in a few minutes, and even obfuscated it. I have no idea why you steal so much code from skilled programmers just because you can barely code by yourself... Maybe you should take a break from that computer and go out for a few hours.

**Comment by lefela4** [comment]
@ZfsrGhS953 Tf are u talking about.

**Comment by lefela4** [comment]
@ZfsrGhS953 I CODDED EVERYTHING IN LIVE WHIT 2 GUY. They can proof you I didnt. I am obstruting my script because I dont want to other to copy my script. I know I take the function to load the config form Multi-ogar. I take anything else. Polars Bots is shit. It my old files. My first code. So can you stop I copy the other and make agar bots ? We will see if u can.

**Comment by lefela4** [comment]
@ZfsrGhS953 Also, Singa bots are PATCHED and they are P2P.

**Comment by lefela4** [comment]
@ZfsrGhS953 I dont trust you. You send me 2 time virus. I think you are in the NuclearC and Sonic team.

**Comment by ZfsrGhS953** [comment]
@lefela4 I am. Do you have a fucking sense of humor? It should be obvious for you that no skilled coder is going to waste time on actually helping an idiot. Singa bots are patched, but they're not P2P. Show me a piece of code from Singa Bots that connects to other peers. Also, I have this screenshot... Now try to prove that you had clone bots before 25th August. ![](http://i.imgur.com/8avo2QT.png)

**Comment by Volanticy** [comment]
Aaaaaaaannnnd thats the end of a big fight :P

**Comment by NuclearC** [comment]
lol what i missed here?

**Comment by Sonicmaster13** [comment]
Lol

**Comment by lefela4** [comment]
No

**Comment by XtremePlayzCODE** [comment]
Yes

**Comment by lefela4** [comment]
@ZfsrGhS953 I have the protocol. You was worng on the TCP thing. Also I want to say you sorry.

**Comment by NuclearC** [comment]
@lefela4 O_O nice you are still alive

**Comment by XtremePlayzCODE** [comment]
does this still even work

**Comment by XtremePlayzCODE** [comment]
![image](https://cloud.githubusercontent.com/assets/15068374/26790208/87b6d4e6-49d8-11e7-9ba4-cc4cb153feb0.png)
im just gonna put this here

**Comment by lefela4** [comment]
@XtremePlayzCODE what is this ?

**Comment by SeeYouNextTime** [comment]
it looks like a picture of bots or something

**Comment by lefela4** [comment]
Yes i know..

**Comment by XtremePlayzCODE** [comment]
it's my own bots

**Comment by lefela4** [comment]
on what game ?

**Comment by XtremePlayzCODE** [comment]
agar

**Comment by XtremePlayzCODE** [comment]
![image](https://cloud.githubusercontent.com/assets/15068374/26791586/3697c8e0-49dd-11e7-8fad-effa84c61d8c.png)
look at the domain, it's real :)

**Comment by lefela4** [comment]
lol do you encrypt ?

**Comment by XtremePlayzCODE** [comment]
on one hand, i want to tell you but on the other i don't trust you because i might be giving you info :p

**Comment by lefela4** [comment]
hahaha

2017-06-05 11:58 GMT-04:00 XtremePlayzCODE <notifications@github.com>:

**Comment by lefela4** [comment]
hahaha

**Comment by lefela4** [comment]
Idc I have the protocol.

**Comment by XtremePlayzCODE** [comment]
oh yeah haha, i'm working on it open-source-ly on [XtremeBotz/T10](https://github.com/XtremeBotz/T10)

**Comment by lefela4** [comment]
Do you have skype?

**Comment by XtremePlayzCODE** [comment]
yes

**Comment by lefela4** [comment]
add me : slithervipbot@gmail.com

**Comment by XtremePlayzCODE** [comment]
added
