### ISSUE TITLE
MESSED UP

### ISSUE THREAD

**Issue by Cr4T1v3** [lefela4/agar_bots_v5#6]
IN FIRST CONNECTION
https://puu.sh/vC4Oy.png
https://puu.sh/vC4Px.png
https://puu.sh/vC4PN.png
https://puu.sh/vC4Q3.png
https://puu.sh/vC4QP.png
https://puu.sh/vC4QZ.png
https://puu.sh/vC4Rz.png
https://puu.sh/vC4RO.png
https://puu.sh/vC4SG.png
https://puu.sh/vC4T3.png
https://puu.sh/vC4Tg.png
https://puu.sh/vC4U3.png
https://puu.sh/vC4Ui.png
https://puu.sh/vC4Uy.png
https://puu.sh/vC4Y5.png
https://puu.sh/vC4Yc.png
https://puu.sh/vC4YF.png
https://puu.sh/vC4YX.png
https://puu.sh/vC4Z7.png
https://puu.sh/vC4Zv.png
https://puu.sh/vC50k.png
https://puu.sh/vC50K.png
https://puu.sh/vC50Q.png

agar.io side
http://puu.sh/vC5qb.png

I HOPE EVERYTHING WILL BE OK.

**Comment by lefela4** [comment]
You proxy are bad.
